### ISSUE TITLE
Support "end_date" in experiment definition to stop assignments on a predetermined date

### ISSUE THREAD

**Issue by bantmen** [Shopify/verdict#63]
Having seamless control over the assignments timeline has been a popular feature request from Shopify teams conducting experiments. The main benefit here is this kind of programmed "scheduling" would ease the coordination burden. For instance, some teams are strict about which day the assignments stop, since they want to avoid the "different day bias", and because they need to coordinate with devs, at times they end up not being able to merge the PR on the correct day, which forces them to wait for another week.

**Comment by pmangg** [comment]
> The main benefit here is this kind of programmed "scheduling" would ease the coordination burden.

Thinking about alternative approaches to adding this feature to the Verdict gem, keeping it "dumb":

1) Wrap `switch` call in the client with time-constraint enforcing logic.
2) Implement the time-constraint enforcement logic inside `qualify` in the experiment definition.  This is a flexible way to incorporate custom qualification logic.

What are some pros and cons of the different approaches?

**Comment by bantmen** [comment]
Since we are centralizing the experimentation tooling in one place, we can no longer afford to keep this gem dumb, as that is causing a duplication of the tooling, along with confusion around how "Verdict" is used at Shopify. For context, our long term plan is for any application to be able to easily benefit from the improved tooling without having to extend the Experiment type themselves.

**Comment by pmangg** [comment]
I think those are great high-level goals, I was thinking outlining the pros and cons of the approaches as this changes the API, and it's used by many downstream clients.  Rough thoughts coming up.

On the change proposed in https://github.com/Shopify/verdict/pull/64:

1) Experiment definition writer is able to specify start and end date on the experiment instance. This could be good if client is manipulating the object.  I've seen cases where client instantiates the experiment object in a ruby file that behaves like [a config file](https://github.com/Shopify/shopify/blob/master/components/launch/app/experiments/compass_card_experiment.rb) (friendly for those who have basic ruby knowledge), and in another file does a lookup to retrieve the object using a symbol, on-the-fly, in order to call `switch`.  The client could call the object again in the file and call the instance methods, but that might be a barrier for some.

2) The method `switch` currently returns `nil` when subject doesn't qualify for the experiment.  This approach overloads the `nil` return value. When you cut a new version, you could announce this API change (will probably need a changelog/release management as this is used by many projects, and it's also open source). Devs need to change their mindset of `nil` return value.

3) Subjects that are assigned to a group and are receiving that group's treatment will receive the `nil` return value treatment when period ends.  Similar to 2), developers will need to design the `nil` treatment accordingly.  Need to change the mindset of Verdict users, as typically they will submit a PR which will make the change they want, instead of having assignments change automatically.

One variation is https://github.com/Shopify/verdict/pull/64 but you'd let previous assignments be returned (i.e., put in your logic in `assign`).  This implementation stops further assignments from happening, but will keep old assignments the same (so subjects will have the same treatment, which in some cases are desirable). 

Another is to let the experiment configuration writer specify start and end date in the block they are passing into `define`.  This could help with 1).

[Last two alternatives](https://github.com/Shopify/verdict/issues/63#issuecomment-607389123) don't require a change to Verdict, though they still return previous assignment value.

Can this be helped by providing an example in the docs for wrapping the switch call in the client with time-constraint enforcing logic?

**Comment by bantmen** [comment]
Good points, let's try to address them.

> as this changes the API, and it's used by many downstream clients

We are extending the API without changing semantics or breaking backwards compatibility, so we would have no adverse impact on downstream clients.

1.
> a ruby file that behaves like a config file

The functions introduced in the PR could be used in that config file pattern. As an example, see the new [unit tests](https://github.com/Shopify/verdict/blob/4f5ad7efe7daacfa91d5ff4fe48c734a5b9d41f9/test/experiment_test.rb#L541). Note that, `define`, used in your config file example, simply calls the `new` method that I am directly calling in the test, so the usages do not differ.

2. In a way, the date scheduling is a special qualifier logic that the library supports for its consumers. In that view, we are keeping the existing semantics: `switch` returns either a group, when the subject is qualified, or `nil` when the subject is not. When the current date is not within experiment's schedule time, no subject is qualified, therefore, `switch` returns `nil` for all subjects. We can write up a changelog to announce this new feature.

3. This is only if the developers are using the scheduling feature. If they are using the scheduling feature, then keeping in mind the `nil` semantics is a relatively low effort action.

> One variation is #64 but you'd let previous assignments be returned

We are also considering supporting that as an additional feature `cooldown_date`. In terms of scheduling, here is the ideal timeline that we would have based on our UX studies:

- Start experiment (no one is part of the experiment before this point) 
- Enter cooldown period (no new assignments are made, existing assignments are returned) 
- End experiment (no one is part of the experiment after this point)

> Can this be helped by providing an example in the docs for wrapping the switch call in the client with time-constraint enforcing logic?

During our UX studies, we have realized that almost no one in the company uses Verdict really the same way and there is ample amount of confusion around how it is used. It's very common that people conflate the tooling that's built around Verdict and what Verdict actually offers. Moreover, it's always more painful than it should be to introduce Verdict to a new environment (unless you are being heavily assisted by experienced people, which only solves the problem to a certain extent). 

The experiment team's bottom line is Verdict currently offers very little compared to the end user's requirements, leading to ad hoc tooling that confuses people (e.g. see the debate around checkout experiment and `disjoint`) or to a situation where the users would rather not experiment. Our overarching strategy, and this is not just about Verdict or necessarily about Verdict, is to unify the tooling and bake in all of the common functionalities.

**Comment by pmangg** [comment]
> We are extending the API without changing semantics or breaking backwards compatibility, so we would have no adverse impact on downstream clients.
> we are keeping the existing semantics: switch returns either a group, when the subject is qualified, or nil when the subject is not. When the current date is not within experiment's schedule time, no subject is qualified

I think that semantics-wise, the return `nil` will be overloaded (API output changes) -- subject not qualifying (returning nil) is different from the experiment not running qualification (which #64 proposes would return nil too), in the latter, the subject still qualifies.  It's better to have it `ExperimentOffScheduleError`.

> We can write up a changelog to announce this new feature.
> If they are using the scheduling feature, then keeping in mind the nil semantics is a relatively low effort action.

I guess it could be low effort depending on the fluency of the user.  From a Verdict user's perspective, if I were to see this feature and I want to use it, the two main things I'll need to consider:

-  Drilling down into 3 in https://github.com/Shopify/verdict/issues/63#issuecomment-607447649, I'll need to handle users that will get nil treatment when end date is reached.  If this is an experiment where a user is receiving the group's treatment multiple times, they will then receive the nil group's treatment after the end date.  Experiment is now over, and once I've analyzed the data, I will then apply the winning group's treatment to everyone (in the basic usage).  So with #64, user will get assignment treatment, nil treatment, then winning group's treatment, where typically it would go from assignment to winning directly.  I might wrap the `switch` statement in such a way that the user will only be switched once instead of twice.

- Drilling down into 2 in https://github.com/Shopify/verdict/issues/63#issuecomment-607447649, I would use `switch` to hard partition of my population based on what I put in qualify, and have surrounding logic around it, sometimes with other experiments for the `nil` population.  With `nil` being overloaded by the new change, the segment that was `nil` before could contain subjects from the experiment that has expired.  Since `switch` is no longer a population partitioning method based on `qualify`, I will need to implement the partitioning outside of `switch` (while minimizing the duplication with what's in `qualify).

**Comment by bantmen** [comment]
> It could be better to not overload and throw ExperimentOffScheduleError instead.

We should not be throwing an error because technically this is not an error that the user has to handle. In general, errors should be sparingly used for actual failures that are not within your control e.g. FileNotFoundError. 

> So with #64, user will get assignment treatment, nil treatment, then winning group's treatment

This depends on how the developer integrates their experiment. Could you expand on it?

Re 3., we still want developers to come back and clean their code. The purpose of this feature is, while the developer is yet to come and disable the feature, the experiment is not running. 

> Since switch is no longer a population partitioning method based on qualify

Is that true though? If your first experiment is returning `nil`, because of scheduling, then technically your populations have changed and therefore could be used for the other experiment. Generally, I don't think it makes sense to chain experiment qualifiers like you described. Each experiment should have a qualification logic that makes sense in isolation. If you have any examples of this, please feel free to send over.

**Comment by pmangg** [comment]
> We should not be throwing an error because technically this is not an error that the user has to handle. In general, errors should be sparingly used for actual failures that are not within your control e.g. FileNotFoundError.

I think that makes sense, I know that there are other opinions out there, and BTW throwing an error is just a way to not overload the nil output, you could achieve that some other ways.  If you do do throw an error, I'd add another public predicate method: `is_active?` that is true when the experiment is within the start and end date.  

> This depends on how the developer integrates their experiment. Could you expand on it?
> Re 3., we still want developers to come back and clean their code. The purpose of this feature is, while the developer is yet to come and disable the feature, the experiment is not running.

Subject is a user.  During the experiment, user X is assigned to group 1 (receiving group 1's treatment), and let's say the nil treatment for the user is control group's treatment (seems to make sense as that's default).  When the experiment ends, shop X receives the control group's treatment.  I analyze the experiment once it ends, decided that group 1 wins, then I would roll out group 1's treatment to everyone.  Now during this experiment, user X received group 1's treatment, then the control group's treatment, and then group 1's treatment.  I'd want user X to receive the same treatment after the experiment ends, until we've decided on what to do.

If the subject is transient, then this wouldn't be so bad.

> Is that true though? If your first experiment is returning nil, because of scheduling, then technically your populations have changed and therefore could be used for the other experiment. Generally, I don't think it makes sense to chain experiment qualifiers like you described. Each experiment should have a qualification logic that makes sense in isolation. If you have any examples of this, please feel free to send over.

It depends on what the API promises me.  If `switch` partitions based on qualification (nil is not qualified, not nil if qualified), which is the current behavior then I would build on top of this assumption.  If it's not, then I'll re-architect it accordingly. 

Example code that assumes hard-partitioning:

```
if Experiments[:experiment_for_subpopulation_X].switch(user) == :group1
  # apply group 1 treatment to subpopulation X users
elsif Experiments[:experiment_for_subpopulation_X].switch(user) == :group2
  # apply group 2 treatment to subpopulation X users
else
  # apply treatment to users that are not coming from subpopulation X
end
```

**Comment by bantmen** [comment]
> I'd want user X to receive the same treatment after the experiment ends, until we've decided on what to do.

In that case, you wouldn't use the feature and get the behaviour that you described. We know that there are people who are asking for the assignments to "stop" after the given schedule, which is what this feature implements. I would prefer for us to ship this feature asap, get some feedback (from people who use start and end dates, others are not impacted in any way), then pivot if needed.

> It depends on what the API promises me.

The API promises to return the group, if there is an assignment, or return `nil` otherwise. This contract is still supported. Merging the feature changes won't break the example that you have posted if you don't use the feature. Let's say that you do use the feature and that the current date is no longer within the schedule of `experiment_for_subpopulation_X`. In that case, the code would run `# apply treatment to users that are not coming from subpopulation X`, which is consistent with the API's contract, because the subject is no longer part of the `experiment_for_subpopulation_X` experiment. That experiment is now over. This behaviour is consistent with the behaviour you would get if you had manually removed this feature, which is the goal of this feature.

**Comment by pmangg** [comment]
> I would prefer for us to ship this feature asap, get some feedback (from people who use start and end dates, others are not impacted in any way), then pivot if needed.

👍 👍 don't let me block you.

> We know that there are people who are asking for the assignments to "stop" after the given schedule, which is what this feature implements.

I think #64 stops returning any assignment (old and new, given a subject), which is related to 3 in https://github.com/Shopify/verdict/issues/63#issuecomment-607447649.  I'd be curious to see how clients could architect around that behaviour in the future (shops getting treatment, then control when the period ends, then getting treatment again).  Let's give it a go, though I'm still skeptical of the utility for experiment subjects that get the treatment multiple times (shops/users, etc).  

> then pivot if needed.

You could also architect it to stop making new assignments, and keep old assignments.

> It depends on what the API promises me.
> The API promises to return the group, if there is an assignment, or return nil otherwise.

Currently: 

Qualification refers to a specific process where a `qualify` method decides if a subject is qualified for the experiment [1], and the method `switch` returns a group if the subject qualifies, and otherwise it returns nil [2].  

Can we make sure to update [2] if we merge this?  Specifically the `case` statement which assumes hard partitioning, similar to the snippet I wrote in [3].  Or, update the meaning of qualification to include the experiment validity date (less preferable).

[1] `A subject is the thing that will be qualified, and if successfull, assigned to a particular group. ` from https://github.com/Shopify/verdict/blob/master/docs/concepts.md#qualifiers.
[2] See the code snippet in https://development.shopify.io/data/platform/experiments/experiment_treatments.
[3] https://github.com/Shopify/verdict/issues/63#issuecomment-607514308
