### ISSUE TITLE
Veredict breaks with Zeitwerk

### ISSUE THREAD

**Issue by masylum** [Shopify/verdict#82]
👋 Hello! First of all, thanks for this awesome gem, we are currently using it in production and we are very happy with it.

We have an issue when updating to Rails 6 and using Zeitwerk (using latest gem version).

We have an experiment in the following folder: `components/public/app/ab_tests/public/remove_confirmation_email_ab_test.rb` and configured `Veredict.

We also have configured verdict to read from that directory:
`Verdict.directory = Rails.root.join('components', 'public', 'app', 'ab_tests', 'public')`.

But when loading the application in production (I bet because of eager loading) it raises the following error:

```
expected file /app-test/components/public/app/ab_tests/public/remove_confirmation_email_ab_test.rb to define constant Public::RemoveConfirmationEmailAbTest, but didn't (Zeitwerk::NameError)
```

I've seen the railtie and the change introduced in https://github.com/Shopify/verdict/pull/61/files but I honestly don't understand what would be the best way to work around the error.

The file defines an experiment as follows:

```rb
unless Verdict.repository.has_key?('remove_confirmation_email_ab_test')
  Public::Experiments::BaseExperiment.define 'remove_confirmation_email_ab_test' do
    # ...
  end
end
```

Thanks in advance,
Pau

**Comment by enriclluelles** [comment]
Hi there,

I work with @masylum at Factorial and I'm posting this here in case someone stumbles upon this issue, to explain what we were doing wrong and how we fixed it

### What were we doing wrong?
We were setting this in our initializer:
```
Verdict.directory = Rails.root.join('components', 'public', 'app', 'ab_tests', 'public')
```
without taking into account that said initializer(since it named "verdict.rb") is loaded *after* the one defined in the railtie https://github.com/Shopify/verdict/blob/master/lib/verdict/railtie.rb#L2 and therefore we were overriding the directory config setting but not telling zeitwerk to ignore it with `Rails.autoloaders.main.ignore(Verdict.directory)`

### How did we fix it?
Making sure that our initializer is either executed after the one defined in the verdict railtie or adding the `Rails.autoloaders.main.ignore(Verdict.directory)` line to it


Cheers and thanks for developing and supporting this lib!

**Comment by masylum** [comment]
Thanks @enriclluelles
